from __future__ import annotations

from enum import Enum


class PlayStyle(Enum):
    CONSERVATIVE = "CONSERVATIVE"
    AGGRESSIVE = "AGGRESSIVE"
    BALANCED = "BALANCED"
    TRICKY = "TRICKY"


class PublicationMode(Enum):
    AUTO = "AUTO"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    HOLD = "HOLD"

class SegmentType(Enum):
    COLD_OPEN = "COLD_OPEN"
    HEADLINE_MATCHUP = "HEADLINE_MATCHUP"
    COACH_SPOTLIGHT = "COACH_SPOTLIGHT"
    PRESSURE_METER = "PRESSURE_METER"
    RIVALRY_HEAT_CHECK = "RIVALRY_HEAT_CHECK"
    TRADE_DESK = "TRADE_DESK"
    FLASHBACK = "FLASHBACK"
    CLOSING_PICKS = "CLOSING_PICKS"


class ShowMode(Enum):
    STANDARD = "STANDARD"
    HIGH_DRAMA = "HIGH_DRAMA"
    QUIET_WEEK = "QUIET_WEEK"
    PLAYOFF_ESCALATION = "PLAYOFF_ESCALATION"


class InputNeed(Enum):
    COACH_PROFILES = "COACH_PROFILES"
    LEAGUE_LORE = "LEAGUE_LORE"
    SEASON_NARRATIVE_STATE = "SEASON_NARRATIVE_STATE"
    COMMISSIONER_SETTINGS = "COMMISSIONER_SETTINGS"